CREATE TABLE Joke(
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(64) NOT NULL,
  Category VARCHAR(64) NOT NULL,
  Body VARCHAR(20000) NOT NULL,
  Author VARCHAR(64) NOT NULL

);

CREATE TABLE Rating(
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  JokeID int,
  RatingValue int(1)
);


ALTER TABLE Rating ADD FOREIGN KEY (JokeID) REFERENCES Joke(ID);

